module ValidWords (wordSet, prefixes, suffixes, sufsuffixes, conceptMap, FeaturedWord(..)) where

import qualified Data.Set as Set
import qualified Data.Map as Map

prefixes :: [String]
prefixes = [ "an" ]

suffixes :: [String]
suffixes = [ "su", "pa", "mo", "ta", "na", "ki", "lo", "la", "en", "nu", "lu" ]

sufsuffixes :: [String]
sufsuffixes = [ "la" ]

wordSet :: [ String]
wordSet = [
    "a",
    "akesi",
    "ala",
    "alasa",
    "ale",
    "anpa",
    "ante",
    "anu",
    "awen",
    "esun",
    "ijo",
    "ike",
    "ilo",
    "insa",
    "jaki",
    "jan",
    "jelo",
    "jo",
    "kala",
    "kalama",
    "kama",
    "kasi",
    "ken",
    "kepeken",
    "kili",
    "kiwen",
    "ko",
    "kon",
    "kule",
    "kulupu",
    "kute",
    "lape",
    "laso",
    "lawa",
    "len",
    "lete",
    "lili",
    "linja",
    "lipu",
    "loje",
    "lon",
    "luka",
    "lukin",
    "lupa",
    "ma",
    "mama",
    "mani",
    "meli",
    "mi",
    "mije",
    "moku",
    "moli",
    "monsi",
    "mu",
    "mun",
    "musi",
    "mute",
    "nanpa",
    "nasa",
    "nasin",
    "nena",
    "ni",
    "nimi",
    "noka",
    "o",
    "olin",
    "ona",
    "open",
    "pakala",
    "pali",
    "palisa",
    "pan",
    "pana",
    "pi",
    "pilin",
    "pimeja",
    "pini",
    "pipi",
    "poka",
    "poki",
    "pona",
    "pu",
    "sama",
    "seli",
    "selo",
    "seme",
    "sewi",
    "sijelo",
    "sike",
    "sin",
    "sina",
    "sinpin",
    "sitelen",
    "sona",
    "soweli",
    "suli",
    "suno",
    "supa",
    "suwi",
    "tan",
    "taso",
    "tawa",
    "telo",
    "tenpo",
    "toki",
    "tomo",
    "tu",
    "unpa",
    "uta",
    "utala",
    "walo",
    "wan",
    "waso",
    "wawa",
    "weka",
    "wile",
    "namako",
    "kin",
    "oko",
    "kipisi",
    "leko",
    "monsuta",
    "tonsi",
    "kijetesantakalu",
    "soko",
    "meso",
    "misikeke"
    ] ++ suffixes

data FeaturedWord = FeaturedWord {
    word :: String,
    prefix :: Maybe String,
    suffix :: Maybe String,
    sufsuffix :: Maybe String
} deriving (Show, Eq)

conceptMap :: Map.Map String FeaturedWord
conceptMap = Map.fromList [
        (fullString, FeaturedWord word prefixOpt suffixOpt sufsuffixOpt) |
            word <- wordSet,
            prefixOpt <- [Nothing] ++ map Just prefixes,
            suffixOpt <- [Nothing] ++ map Just suffixes,
            sufsuffixOpt <- [Nothing] ++ map Just sufsuffixes,
            let prefix = maybe "" id prefixOpt,
            let suffix = maybe "" id suffixOpt,
            let sufsuffix = maybe "" id sufsuffixOpt,
            let fullString = prefix ++ word ++ suffix ++ sufsuffix
    ]