use lazy_static::lazy_static;

pub(super) const PREFIXES: [&str; 1] = ["an"];

pub(super) const SUFFIXES: [&str; 11] = [
    "su", "pa", "mo", "ta", "na", "ki", "lo", "un", "nu", "lu", "we",
];

pub(super) const SUFSUFFIXES: [&str; 1] = ["la"];

pub(super) const ROOTS: [&str; 129] = [
    "en",
    "a",
    "akesi",
    "ala",
    "alasa",
    "ale",
    "anpa",
    "ante",
    "anu",
    "awen",
    "esun",
    "ijo",
    "ike",
    "ilo",
    "insa",
    "jaki",
    "jan",
    "jelo",
    "jo",
    "kala",
    "kalama",
    "kama",
    "kasi",
    "ken",
    "kepeken",
    "kili",
    "kiwen",
    "ko",
    "kon",
    "kule",
    "kulupu",
    "kute",
    "lape",
    "laso",
    "lawa",
    "len",
    "lete",
    "lili",
    "linja",
    "lipu",
    "loje",
    "lon",
    "luka",
    "lukin",
    "lupa",
    "ma",
    "mama",
    "mani",
    "meli",
    "mi",
    "mije",
    "moku",
    "moli",
    "monsi",
    "mu",
    "mun",
    "musi",
    "mute",
    "nanpa",
    "nasa",
    "nasin",
    "nena",
    "ni",
    "nimi",
    "no",
    "noka",
    "o",
    "olin",
    "ona",
    "open",
    "pakala",
    "pali",
    "palisa",
    "pan",
    "pana",
    "pi",
    "pilin",
    "pimeja",
    "pini",
    "pipi",
    "poka",
    "poki",
    "pona",
    "pu",
    "sama",
    "seli",
    "selo",
    "seme",
    "sewi",
    "sijelo",
    "sike",
    "sin",
    "sina",
    "sinpin",
    "sitelen",
    "sona",
    "soweli",
    "suli",
    "suno",
    "supa",
    "suwi",
    "tan",
    "taso",
    "tawa",
    "telo",
    "tenpo",
    "toki",
    "tomo",
    "tu",
    "unpa",
    "uta",
    "utala",
    "walo",
    "wan",
    "waso",
    "wawa",
    "weka",
    "wile",
    "namako",
    "kin",
    "oko",
    "kipisi",
    "leko",
    "monsuta",
    "tonsi",
    "kijetesantakalu",
    "soko",
    "meso",
    "misikeke",
];

pub(super) const LITERALS: [&str; 88] = [
    "A", "E", "I", "O", "U", "N", "KA", "KE", "KI", "KO", "KU", "LA", "LI", "LE", "LO", "LU", "MA",
    "ME", "MI", "MO", "MU", "NA", "NE", "NI", "NO", "NU", "PA", "PE", "PI", "PO", "PU", "SA", "SE",
    "SI", "SO", "SU", "TA", "TE", "TO", "TU", "JA", "JE", "JO", "JU", "WA", "WE", "WI", "KAN",
    "KEN", "KIN", "KON", "KUN", "LAN", "LIN", "LEN", "LON", "LUN", "MAN", "MEN", "MIN", "MON",
    "MUN", "NAN", "NEN", "NIN", "NON", "NUN", "PAN", "PEN", "PIN", "PON", "PUN", "SAN", "SEN",
    "SIN", "SON", "SUN", "TAN", "TEN", "TON", "TUN", "JAN", "JEN", "JON", "JUN", "WAN", "WEN",
    "WIN",
];
